name: Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/react-app
  CONTAINER_NAME: react-app
  HOST_PORT: 80
  CONTAINER_PORT: 80

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate required secrets
        run: |
          missing=0
          [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] && echo "Missing secret: DOCKERHUB_USERNAME" && missing=1
          [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ] && echo "Missing secret: DOCKERHUB_TOKEN" && missing=1
          [ -z "${{ secrets.VPS_HOST }}" ] && echo "Missing secret: VPS_HOST" && missing=1
          [ -z "${{ secrets.VPS_USER }}" ] && echo "Missing secret: VPS_USER" && missing=1
          [ -z "${{ secrets.VPS_SSH_KEY }}" ] && echo "Missing secret: VPS_SSH_KEY" && missing=1
          if [ "$missing" -eq 1 ]; then
            echo "One or more required secrets are missing. Add them in Settings → Secrets and variables → Actions."
            exit 1
          fi
          echo "IMAGE_NAME will be: ${{ env.IMAGE_NAME }}"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN
          script: |
            if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ]; then
              echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            fi
            docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
            if [ "$(docker ps -aq -f name=${{ env.CONTAINER_NAME }})" ]; then
              docker rm -f ${{ env.CONTAINER_NAME }}
            fi
            docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.HOST_PORT }}:${{ env.CONTAINER_PORT }} --restart unless-stopped ${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker image prune -f
